imageTag: multiarch

resources:
  requests: {}

tolerations:
  - key: "app"
    operator: "Equal"
    value: "minecraft"
    effect: "NoSchedule"

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 60

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 60

minecraftServer:
  # This must be overridden, since we can't accept this for the user.
  eula: "TRUE"

  # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
  version: "1.16.5"
  # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTB", "SPONGEVANILLA"
  type: "PAPER"

  # Max view distance (in chunks).
  viewDistance: 7

  # Message of the Day
  motd: "Welcome to Minecraft on Kubernetes on Rapsberry Pi!"

  # If you adjust this, you may need to adjust resources.requests above to match.
  # If you are running on raspberry pi 4 you can utilize a lot more
  memory: 512M

persistence:
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: true
    Size: 10Gi
